services:
    app:
        build: .
        container_name: poll_management_app
        working_dir: /var/www/html
        ports:
            - "8000:80"
            - "8080:8080"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: Root@Pass@123
            MYSQL_DATABASE: poll_management
            MYSQL_USER: poll_management
            MYSQL_PASSWORD: poll_management
        ports:
            - "3309:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
